//! ASS 卡拉OK歌词生成
//!
//! 三个 Style：`orig`/`ts`/`roma`；原文行用 `{\kf<厘秒>}` 逐字，译文/罗马音为普通行。

use std::fmt::Write;

/// 逐字单元：字起始/结束毫秒 + 文本。KRC 直接给出字时长；QRC 只给起始时间，
/// 由 [`words_from_starts`] 补出 `end_ms`
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Word {
    pub start_ms: i64,
    pub end_ms: i64,
    pub text: String,
}

/// 秒 → `00:00:03.24`（时:分:秒.厘秒）
fn format_ass_time(secs: f64) -> String {
    let total_cs = (secs * 100.0).round() as i64;
    let h = total_cs / 360_000;
    let m = (total_cs % 360_000) / 6_000;
    let s = (total_cs % 6_000) / 100;
    let cs = total_cs % 100;
    format!("{h:02}:{m:02}:{s:02}.{cs:02}")
}

fn format_ass_time_ms(ms: i64) -> String {
    format_ass_time(ms as f64 / 1000.0)
}

/// 生成 ASS 文件头 + 三个 Style（orig/ts/roma）
pub fn ass_header(title: &str) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "[Script Info]");
    let _ = writeln!(s, "; Script generated by Mercurial Player");
    let _ = writeln!(s, "Title: {title}");
    let _ = writeln!(s, "ScriptType: v4.00+");
    let _ = writeln!(s, "Timer: 100.0000");
    let _ = writeln!(s);
    let _ = writeln!(s, "[V4+ Styles]");
    let _ = writeln!(
        s,
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
    );
    for (name, size) in [("orig", 20u32), ("ts", 20), ("roma", 20)] {
        let _ = writeln!(
            s,
            "Style: {name},Arial,{size},&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1"
        );
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "[Events]");
    let _ = writeln!(
        s,
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
    );
    s
}

/// 由「字起始时间 + 文本」补出 [`Word`]：每字结束 = 下一字起始，末字结束 = `end_ms`（QQ QRC 用）
pub fn words_from_starts(segs: &[(i64, String)], end_ms: i64) -> Vec<Word> {
    segs.iter()
        .enumerate()
        .map(|(i, (start_ms, text))| Word {
            start_ms: *start_ms,
            end_ms: if i + 1 < segs.len() {
                segs[i + 1].0
            } else {
                end_ms
            },
            text: text.clone(),
        })
        .collect()
}

/// 生成一条 Dialogue：`words` 多于一个单元时按 `lyrics_line2asstext` 输出 `{\kf}` 逐字
/// （每字时长取 `|end - start|`），单单元或 `None` 时输出 `plain` 普通文本行
pub fn dialogue(
    start_ms: i64,
    end_ms: i64,
    style: &str,
    words: Option<&[Word]>,
    plain: &str,
) -> String {
    let start = format_ass_time_ms(start_ms);
    let end = format_ass_time_ms(end_ms);
    let text = match words {
        Some(words) if words.len() > 1 => {
            let mut out = String::new();
            for word in words {
                let kf = (word.end_ms - word.start_ms).unsigned_abs() / 10; // 毫秒 → 厘秒
                let _ = write!(out, "{{\\kf{kf}}}{}", word.text);
            }
            out
        }
        _ => plain.to_string(),
    };
    format!("Dialogue: 0,{start},{end},{style},,0,0,0,,{text}\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn 时间格式化为ass格式() {
        assert_eq!(format_ass_time(3.24), "00:00:03.24");
        assert_eq!(format_ass_time(61.005), "00:01:01.01");
        assert_eq!(format_ass_time(3661.0), "01:01:01.00");
    }

    #[test]
    fn 生成头与样式() {
        let header = ass_header("RISE");
        assert!(header.contains("[Script Info]"));
        assert!(header.contains("Title: RISE"));
        assert!(header.contains("Style: orig,Arial,20,"));
        assert!(header.contains("Style: ts,Arial,20,"));
        assert!(header.contains("Style: roma,Arial,20,"));
        assert!(header.contains("[Events]"));
    }

    #[test]
    fn 逐字行与普通行() {
        let words = words_from_starts(
            &[
                (3240, "徐".to_string()),
                (3380, "々".to_string()),
                (3540, "に".to_string()),
            ],
            6690,
        );
        let line = dialogue(3240, 6690, "orig", Some(&words), "");
        assert!(line.starts_with("Dialogue: 0,00:00:03.24,00:00:06.69,orig,,0,0,0,,"));
        assert!(line.contains("{\\kf14}徐"));
        assert!(line.contains("{\\kf16}々"));
        // 末字时长 = 6690-3540=3150ms → 315 厘秒
        assert!(line.contains("{\\kf315}に"));

        let plain = dialogue(3240, 6690, "ts", None, "那缓缓变化的姿态");
        assert!(plain.starts_with("Dialogue: 0,00:00:03.24,00:00:06.69,ts,,"));
        assert!(plain.contains("那缓缓变化的姿态"));
    }

    #[test]
    fn 单字行不入逐字标记() {
        let words = vec![Word {
            start_ms: 1000,
            end_ms: 3000,
            text: "作词：李健".to_string(),
        }];
        let line = dialogue(1000, 3000, "orig", Some(&words), "作词：李健");
        assert_eq!(
            line,
            "Dialogue: 0,00:00:01.00,00:00:03.00,orig,,0,0,0,,作词：李健\n"
        );
        assert!(!line.contains("\\kf"));

        // 空单元列表同样退化为普通文本
        let empty: Vec<Word> = Vec::new();
        assert!(dialogue(0, 10, "orig", Some(&empty), "x").ends_with(",x\n"));
    }

    #[test]
    fn 逐字时长取字自身区间() {
        // 来自 KRC 的字时长与「下一字起始」不同时，以字自身区间为准
        let words = vec![
            Word {
                start_ms: 0,
                end_ms: 500,
                text: "a".to_string(),
            },
            Word {
                start_ms: 1000,
                end_ms: 1400,
                text: "b".to_string(),
            },
        ];
        let line = dialogue(0, 2000, "orig", Some(&words), "");
        assert!(line.contains("{\\kf50}a"));
        assert!(line.contains("{\\kf40}b"));
    }
}
